version: '3.1'

services:
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
    volumes:
      - ./docker-volumes/otel:/etc/otel/collector
    env_file:
      - ./docker-volumes/otel/.env